updated

diff --git a/get b/get
--- a/get
+++ b/get
@@ -14,7 +14,7 @@ URL="$URL/zbash_config.sh?v_$(date +"%S")=$RANDOM"
 echo "[Downloading] $URL" 1>&2
 SCRIPT="$(curl -sL "$URL")"
 if [ -z "$SCRIPT" ]; then
-  echo 1>&2 "Error when downloading script. Script empty"
+  echo 1>&2 "Error when downloading script. Script empty or failed to download."
   exit 2
 fi
 if [ "$SCRIPT" == "Not Found" ]; then
